name: Deploy TCIOE Website to VPS
on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Build & Deploy to VPS
    runs-on: self-hosted
    env:
      NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${{ secrets.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Unified VPS Deployer
        run: |
          cd /srv/deployer
          node deploy.js $GITHUB_REPOSITORY
